# \cite(ankitaImprovedOpticalBiosensor2022) => sensor_1


wavelength:
  range: [700, 900]
  step: 0.1


sensor:
  reference_wavelength_nm: 800.0

  si_periods: 3

  metal_thickness_nm: 15.0

  defect_thickness_nm: 7000.0

  angle_deg: 86.0

  mode: "TM"


data_set:

  save_generated_data_path: "./data/malaria_1dpc_2022.h5"

  num_samples: 4000

  stages:
    - normal
    - ring
    - trophozoite
    - schizont